### ISSUE TITLE
Date/time parsing errors raise exceptions

### ISSUE THREAD

**Issue by peterk87** [peterk87/shiptv#1]
* Standalone HTML Interactive Phylogenetic Tree Viz version: 0.1.0
* Python version: 3.6.7
* Operating System: Ubuntu 16.04.6 LTS

### Description

Some sequences from NCBI have strange formatting for the `collection_date` metadata such as `1994/1995`. 

`shiptv` shouldn't be throwing an exception, but should just return a null value in these cases where the date/time cannot be parsed easily. 

### What I Did

```
$ shiptv -r refs.gb -n tree.newick -o tree.html -m md.tsv

Traceback (most recent call last):
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py", line 1861, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/bin/shiptv", line 10, in <module>
    sys.exit(main())
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/shiptv/cli.py", line 79, in main
    try_fix_collection_date_metadata(df_metadata)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/shiptv/shiptv.py", line 171, in try_fix_collection_date_metadata
    fix_collection_date(df_metadata)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/shiptv/shiptv.py", line 61, in fix_collection_date
    years = [x.year if not pd.isnull(x) else x for x in pd.to_datetime(df_metadata.collection_date)]
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 592, in to_datetime
    values = convert_listlike(arg._values, True, format)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 302, in _convert_listlike_datetimes
    allow_object=True)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py", line 1866, in objects_to_datetime64ns
    raise e
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py", line 1857, in objects_to_datetime64ns
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 460, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 685, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 809, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 803, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 99, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/CSCScience.ca/pkruczkiewicz/miniconda3/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 648, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: ('Unknown string format:', '1994/1995')
```

**Comment by peterk87** [comment]
Fixed in #4
